fragment GqlLge on GqlLge {
    address
    adminAddress
    adminIsMultisig
    bannerImageUrl
    collateralAddress
    collateralAmount
    collateralDecimals
    collateralEndWeight
    collateralStartWeight
    description
    discordUrl
    endTimestamp
    id
    mediumUrl
    name
    startTimestamp
    swapFee
    telegramUrl
    tokenAddress
    tokenAmount
    tokenDecimals
    tokenEndWeight
    tokenIconUrl
    tokenStartWeight
    tokenSymbol
    twitterUrl
    websiteUrl
}

query GetLge($id: ID!) {
    lge: lge(id: $id) {
        ...GqlLge
    }
}
