query GetPool($id: String!) {
    pool: poolGetPool(id: $id) {
        id
        address
        name
        owner
        decimals
        factory
        symbol
        createTime
        dynamicData {
            poolId
            swapEnabled
            totalLiquidity
            totalLiquidity24hAgo
            totalShares
            totalShares24hAgo
            fees24h
            swapFee
            volume24h
            fees48h
            volume48h
            lifetimeVolume
            lifetimeSwapFees
            holdersCount
            swapsCount
            sharePriceAth
            sharePriceAthTimestamp
            sharePriceAtl
            sharePriceAtlTimestamp
            totalLiquidityAth
            totalLiquidityAthTimestamp
            totalLiquidityAtl
            totalLiquidityAtlTimestamp
            volume24hAth
            volume24hAthTimestamp
            volume24hAtl
            volume24hAtlTimestamp
            fees24hAth
            fees24hAthTimestamp
            fees24hAtl
            fees24hAtlTimestamp
            apr {
                hasRewardApr
                thirdPartyApr
                nativeRewardApr
                swapApr
                total
                items {
                    id
                    title
                    apr
                    subItems {
                        id
                        title
                        apr
                    }
                }
            }
        }
        allTokens {
            id
            address
            name
            symbol
            decimals
            isNested
            isPhantomBpt
        }
        displayTokens {
            id
            address
            name
            weight
            symbol
            nestedTokens {
                id
                address
                name
                weight
                symbol
            }
        }
        staking {
            id
            type
            address
            farm {
                id
                beetsPerBlock
                rewarders {
                    id
                    address
                    tokenAddress
                    rewardPerSecond
                }
            }
            gauge {
                id
                gaugeAddress
                rewards {
                    id
                    rewardPerSecond
                    tokenAddress
                }
            }
            reliquary {
                levels {
                    level
                    balance
                    apr
                    allocationPoints
                }
                beetsPerSecond
                totalBalance
            }
        }
        investConfig {
            singleAssetEnabled
            proportionalEnabled
            options {
                poolTokenIndex
                poolTokenAddress
                tokenOptions {
                    ... on GqlPoolToken {
                        ...GqlPoolToken
                    }
                }
            }
        }
        withdrawConfig {
            singleAssetEnabled
            proportionalEnabled
            options {
                poolTokenIndex
                poolTokenAddress
                tokenOptions {
                    ... on GqlPoolToken {
                        ...GqlPoolToken
                    }
                }
            }
        }
        ... on GqlPoolWeighted {
            nestingType
            tokens {
                ... on GqlPoolToken {
                    ...GqlPoolToken
                }
                ... on GqlPoolTokenLinear {
                    ...GqlPoolTokenLinear
                }
                ... on GqlPoolTokenPhantomStable {
                    ...GqlPoolTokenPhantomStable
                }
            }
        }
        ... on GqlPoolStable {
            amp
            tokens {
                ... on GqlPoolToken {
                    ...GqlPoolToken
                }
            }
        }
        ... on GqlPoolMetaStable {
            amp
            tokens {
                ... on GqlPoolToken {
                    ...GqlPoolToken
                }
            }
        }
        ... on GqlPoolElement {
            unitSeconds
            principalToken
            baseToken
            tokens {
                ... on GqlPoolToken {
                    ...GqlPoolToken
                }
            }
        }
        ... on GqlPoolPhantomStable {
            amp
            nestingType
            tokens {
                ... on GqlPoolToken {
                    ...GqlPoolToken
                }
                ... on GqlPoolTokenLinear {
                    ...GqlPoolTokenLinear
                }
                ... on GqlPoolTokenPhantomStable {
                    ...GqlPoolTokenPhantomStable
                }
            }
        }
        ... on GqlPoolLinear {
            mainIndex
            wrappedIndex
            lowerTarget
            upperTarget
            tokens {
                ... on GqlPoolToken {
                    ...GqlPoolToken
                }
            }
        }
        ... on GqlPoolLiquidityBootstrapping {
            name
            nestingType
            tokens {
                ... on GqlPoolToken {
                    ...GqlPoolToken
                }
                ... on GqlPoolTokenLinear {
                    ...GqlPoolTokenLinear
                }
                ... on GqlPoolTokenPhantomStable {
                    ...GqlPoolTokenPhantomStable
                }
            }
        }
    }
}

fragment GqlPoolToken on GqlPoolToken {
    id
    index
    name
    symbol
    balance
    address
    priceRate
    decimals
    weight
    totalBalance
}

fragment GqlPoolTokenLinear on GqlPoolTokenLinear {
    id
    index
    name
    symbol
    balance
    address
    priceRate
    decimals
    weight
    mainTokenBalance
    wrappedTokenBalance
    totalMainTokenBalance
    totalBalance
    pool {
        id
        name
        symbol
        address
        owner
        factory
        createTime
        wrappedIndex
        mainIndex
        upperTarget
        lowerTarget
        totalShares
        totalLiquidity
        bptPriceRate
        tokens {
            ... on GqlPoolToken {
                ...GqlPoolToken
            }
        }
    }
}

fragment GqlPoolTokenPhantomStable on GqlPoolTokenPhantomStable {
    id
    index
    name
    symbol
    balance
    address
    weight
    priceRate
    decimals
    totalBalance
    pool {
        id
        name
        symbol
        address
        owner
        factory
        createTime
        totalShares
        totalLiquidity
        nestingType
        swapFee
        amp
        tokens {
            ... on GqlPoolToken {
                ...GqlPoolToken
            }
            ... on GqlPoolTokenLinear {
                ...GqlPoolTokenLinear
            }
        }
    }
}

query GetPoolSwaps($first: Int, $skip: Int, $where: GqlPoolSwapFilter) {
    swaps: poolGetSwaps(first: $first, skip: $skip, where: $where) {
        id
        poolId
        timestamp
        tokenAmountIn
        tokenAmountOut
        tokenIn
        tokenOut
        tx
        userAddress
        valueUSD
    }
}

query GetPoolJoinExits($first: Int, $skip: Int, $poolId: String!) {
    joinExits: poolGetJoinExits(first: $first, skip: $skip, where: { poolIdIn: [$poolId] }) {
        id
        timestamp
        tx
        type
        poolId
        valueUSD
        amounts {
            address
            amount
        }
    }
}

query GetPoolBptPriceChartData($address: String!, $range: GqlTokenChartDataRange!) {
    prices: tokenGetPriceChartData(address: $address, range: $range) {
        id
        price
        timestamp
    }
}

query GetPoolUserJoinExits($first: Int, $skip: Int, $poolId: String!) {
    joinExits: userGetPoolJoinExits(poolId: $poolId, first: $first, skip: $skip) {
        id
        timestamp
        tx
        type
        poolId
        valueUSD
        amounts {
            address
            amount
        }
    }
}

query GetUserSwaps($first: Int, $skip: Int, $poolId: String!) {
    swaps: userGetSwaps(first: $first, skip: $skip, poolId: $poolId) {
        id
        poolId
        timestamp
        tokenAmountIn
        tokenAmountOut
        tokenIn
        tokenOut
        tx
        valueUSD
    }
}

query GetPoolSnapshots($poolId: String!, $range: GqlPoolSnapshotDataRange!) {
    snapshots: poolGetSnapshots(id: $poolId, range: $range) {
        id
        timestamp
        totalLiquidity
        volume24h
        fees24h
        sharePrice
    }
}

query GetPoolTokensDynamicData($addresses: [String!]!) {
    staticData: tokenGetTokensData(addresses: $addresses) {
        id
        tokenAddress
        description
        discordUrl
        telegramUrl
        twitterUsername
        websiteUrl
    }
    dynamicData: tokenGetTokensDynamicData(addresses: $addresses) {
        ...GqlTokenDynamicData
    }
}
