query SftmxGetStakingData {
    sftmxGetStakingData {
        exchangeRate
        maintenancePaused
        maxDepositLimit
        minDepositLimit
        numberOfVaults
        stakingApr
        totalFtmAmount
        totalFtmAmountInPool
        totalFtmAmountStaked
        undelegatePaused
        withdrawPaused
        withdrawalDelay
    }
}
