query getLges {
    lges: lges {
        address
        adminAddress
        adminIsMultisig
        bannerImageUrl
        collateralAmount
        collateralEndWeight
        collateralStartWeight
        collateralTokenAddress
        description
        discordUrl
        endDate
        id
        mediumUrl
        name
        startDate
        swapFeePercentage
        telegramUrl
        tokenAmount
        tokenContractAddress
        tokenEndWeight
        tokenIconUrl
        tokenStartWeight
        twitterUrl
        websiteUrl
    }
}
