query GetAppGlobalData {
    tokenGetTokens {
        address
        name
        symbol
        decimals
        chainId
        logoURI
        priority
        tradable
    }
    tokenGetCurrentPrices {
        price
        address
    }
}

query GetTokens {
    tokens: tokenGetTokens {
        address
        name
        symbol
        decimals
        chainId
        logoURI
        priority
        tradable
    }
}

query GetTokenPrices {
    tokenPrices: tokenGetCurrentPrices {
        price
        address
    }
}
