query GetReliquaryFarmSnapshots($id: String!, $range: GqlPoolSnapshotDataRange!) {
    snapshots: poolGetReliquaryFarmSnapshots(id: $id, range: $range) {
        id
        farmId
        timestamp
        totalBalance
        totalLiquidity
        levelBalances {
            id
            level
            balance
        }
        relicCount
        totalBalance
        userCount
        tokenBalances {
            id
            address
            balance
            symbol
        }
    }
}
