query GetUserBalances {
    balances: userGetPoolBalances {
        poolId
        tokenAddress
        tokenPrice
        totalBalance
        stakedBalance
        walletBalance
    }
    fbeetsBalance: userGetFbeetsBalance {
        totalBalance
        stakedBalance
        walletBalance
    }
}
