query GetUserData {
    balances: userGetPoolBalances {
        poolId
        tokenAddress
        tokenPrice
        totalBalance
        stakedBalance
        walletBalance
    }
    fbeetsBalance: userGetFbeetsBalance {
        totalBalance
        stakedBalance
        walletBalance
    }
    staking: userGetStaking {
        id
        chain
        type
        address
        chain
        farm {
            id
            beetsPerBlock
            rewarders {
                id
                address
                tokenAddress
                rewardPerSecond
            }
        }
        gauge {
            id
            gaugeAddress
            version
            status
            otherGauges {
                gaugeAddress
                version
                status
                id
                rewards {
                    id
                    tokenAddress
                    rewardPerSecond
                }
            }
            rewards {
                id
                rewardPerSecond
                tokenAddress
            }
            workingSupply
        }
    }
    veBALUserBalance: veBalGetUserBalance
}

mutation UserSyncBalance($poolId: String!) {
    userSyncBalance(poolId: $poolId)
}
