query GetLinearPools {
    pools: poolGetLinearPools {
        ...GqlPoolLinear
    }
}

fragment GqlPoolLinear on GqlPoolLinear {
    id
    address
    name
    owner
    decimals
    factory
    symbol
    createTime
    dynamicData {
        poolId
        swapEnabled
        totalLiquidity
        totalLiquidity24hAgo
        totalShares
        totalShares24hAgo
        fees24h
        swapFee
        volume24h
        fees48h
        volume48h
        apr {
            hasRewardApr
            thirdPartyApr
            nativeRewardApr
            swapApr
            total
            items {
                id
                title
                apr
                subItems {
                    id
                    title
                    apr
                }
            }
        }
    }
    mainIndex
    wrappedIndex
    lowerTarget
    upperTarget
    tokens {
        id
        index
        name
        symbol
        balance
        address
        priceRate
        decimals
        weight
        totalBalance
    }
}
