query GetLinearPools {
    pools: poolGetLinearPools {
        ...GqlPoolLinear
    }
}

fragment GqlPoolLinear on GqlPoolLinear {
    id
    address
    name
    owner
    decimals
    factory
    symbol
    createTime
    dynamicData {
        poolId
        swapEnabled
        totalLiquidity
        totalLiquidity24hAgo
        totalShares
        totalShares24hAgo
        fees24h
        swapFee
        volume24h
        fees48h
        volume48h
        apr {
            hasRewardApr
            thirdPartyApr {
                ... on GqlPoolAprTotal {
                    total
                }
                ... on GqlPoolAprRange {
                    min
                    max
                }
            }
            nativeRewardApr {
                ... on GqlPoolAprTotal {
                    total
                }
                ... on GqlPoolAprRange {
                    min
                    max
                }
            }
            swapApr
            apr {
                ... on GqlPoolAprTotal {
                    total
                }
                ... on GqlPoolAprRange {
                    min
                    max
                }
            }
            items {
                id
                title
                apr {
                    ... on GqlPoolAprTotal {
                        total
                    }
                    ... on GqlPoolAprRange {
                        min
                        max
                    }
                }
                subItems {
                    id
                    title
                    apr {
                        ... on GqlPoolAprTotal {
                            total
                        }
                        ... on GqlPoolAprRange {
                            min
                            max
                        }
                    }
                }
            }
        }
    }
    mainIndex
    wrappedIndex
    lowerTarget
    upperTarget
    tokens {
        id
        index
        name
        symbol
        balance
        address
        priceRate
        decimals
        weight
        totalBalance
    }
}
