query TokenGetHistoricalPrices($addresses: [String!]!) {
    historicalPrices: tokenGetHistoricalPrices(addresses: $addresses) {
        address
        prices {
            price
            timestamp
        }
    }
}
