query GetPools(
    $first: Int
    $skip: Int
    $orderBy: GqlPoolOrderBy
    $orderDirection: GqlPoolOrderDirection
    $where: GqlPoolFilter
    $textSearch: String
) {
    poolGetPools(
        first: $first
        skip: $skip
        orderBy: $orderBy
        orderDirection: $orderDirection
        where: $where
        textSearch: $textSearch
    ) {
        id
        address
        name
        symbol
        createTime
        dynamicData {
            totalLiquidity
            totalShares
            fees24h
            swapFee
            volume24h
            apr {
                hasRewardApr
                thirdPartyApr
                nativeRewardApr
                swapApr
                total
                items {
                    title
                    apr
                    subItems {
                        title
                        apr
                    }
                }
            }
        }
        allTokens {
            id
            address
            isNested
            isPhantomBpt
        }
    }
    count: poolGetPoolsCount(
        first: $first
        skip: $skip
        orderBy: $orderBy
        orderDirection: $orderDirection
        where: $where
        textSearch: $textSearch
    )
}

#not sure why, but can't expand the fragment in the query above, probably has to do with the interface type
fragment GqlPoolBase on GqlPoolBase {
    id
    address
    name
    symbol
    createTime
    dynamicData {
        totalLiquidity
        totalShares
        fees24h
        swapFee
        volume24h
        apr {
            hasRewardApr
            thirdPartyApr
            nativeRewardApr
            swapApr
            total
            items {
                title
                apr
                subItems {
                    title
                    apr
                }
            }
        }
    }
    allTokens {
        id
        address
        isNested
        isPhantomBpt
    }
}
