query GetPools(
    $first: Int
    $skip: Int
    $orderBy: GqlPoolOrderBy
    $orderDirection: GqlPoolOrderDirection
    $where: GqlPoolFilter
    $textSearch: String
) {
    poolGetPools(
        first: $first
        skip: $skip
        orderBy: $orderBy
        orderDirection: $orderDirection
        where: $where
        textSearch: $textSearch
    ) {
        ...GqlPoolMinimal
    }
    count: poolGetPoolsCount(
        first: $first
        skip: $skip
        orderBy: $orderBy
        orderDirection: $orderDirection
        where: $where
        textSearch: $textSearch
    )
}

#not sure why, but can't expand the fragment in the query above, probably has to do with the interface type
fragment GqlPoolMinimal on GqlPoolMinimal {
    id
    address
    name
    symbol
    createTime
    version
    dynamicData {
        totalLiquidity
        totalShares
        fees24h
        swapFee
        volume24h
        apr {
            hasRewardApr
            thirdPartyApr {
                ... on GqlPoolAprTotal {
                    total
                }
                ... on GqlPoolAprRange {
                    min
                    max
                }
            }
            nativeRewardApr {
                ... on GqlPoolAprTotal {
                    total
                }
                ... on GqlPoolAprRange {
                    min
                    max
                }
            }
            swapApr
            apr {
                ... on GqlPoolAprTotal {
                    total
                }
                ... on GqlPoolAprRange {
                    min
                    max
                }
            }
            items {
                id
                title
                apr {
                    ... on GqlPoolAprTotal {
                        total
                    }
                    ... on GqlPoolAprRange {
                        min
                        max
                    }
                }
                subItems {
                    id
                    title
                    apr {
                        ... on GqlPoolAprTotal {
                            total
                        }
                        ... on GqlPoolAprRange {
                            min
                            max
                        }
                    }
                }
            }
        }
    }
    allTokens {
        id
        address
        isNested
        isPhantomBpt
        weight
        symbol
    }
    displayTokens {
        id
        address
        name
        weight
        symbol
        nestedTokens {
            id
            address
            name
            weight
            symbol
        }
    }
    staking {
        id
        type
        address
        farm {
            id
            beetsPerBlock
            rewarders {
                id
                address
                tokenAddress
                rewardPerSecond
            }
        }
    }
}
