query GetSorSwaps(
    $tokenIn: String!
    $tokenOut: String!
    $swapType: GqlSorSwapType!
    $swapAmount: BigDecimal!
    $swapOptions: GqlSorSwapOptionsInput!
) {
    swaps: sorGetSwaps(
        tokenIn: $tokenIn
        tokenOut: $tokenOut
        swapType: $swapType
        swapAmount: $swapAmount
        swapOptions: $swapOptions
    ) {
        tokenIn
        tokenOut
        swapAmount
        tokenAddresses
        swapType
        marketSp
        swaps {
            poolId
            amount
            userData
            assetInIndex
            assetOutIndex
        }
        returnAmount
        returnAmountScaled
        returnAmountFromSwaps
        returnAmountConsideringFees
        swapAmount
        swapAmountScaled
        swapAmountForSwaps
        routes {
            tokenIn
            tokenOut
            tokenInAmount
            tokenOutAmount
            share
            hops {
                poolId
                tokenIn
                tokenOut
                tokenInAmount
                tokenOutAmount
            }
        }
    }
}
