query GetTokens {
    tokens: tokenGetTokens {
        address
        name
        symbol
        decimals
        chainId
        logoURI
    }
}

query GetTokenPrices {
    tokenPrices: tokenGetCurrentPrices {
        price
        address
    }
}
