query GetSorSwaps($input: GqlSorGetSwapsInput!) {
    swaps: sorGetSwaps(input: $input) {
        tokenIn
        tokenOut
        swapAmount
        tokenAddresses
        swaps {
            poolId
            amount
            userData
            assetInIndex
            assetOutIndex
        }
        returnAmount
        returnAmountFromSwaps
        returnAmountConsideringFees
        swapAmount
        swapAmountForSwaps
        routes {
            tokenIn
            tokenOut
            tokenInAmount
            tokenOutAmount
            share
            hops {
                poolId
                tokenIn
                tokenOut
                tokenInAmount
                tokenOutAmount
            }
        }
    }
}
