query GetAppGlobalData {
    tokenGetTokens {
        address
        name
        symbol
        decimals
        chainId
        logoURI
        priority
        tradable
    }
    #tokenGetCurrentPrices {
    #    price
    #    address
    #}
    beetsGetFbeetsRatio
    blocksGetBlocksPerDay
    blocksGetAverageBlockTime
}

query GetAppGlobalPollingData {
    tokenGetCurrentPrices {
        price
        address
    }
    protocolMetrics {
        totalLiquidity
        totalSwapVolume
        totalSwapFee
        poolCount
        swapFee24h
        swapVolume24h
    }
    blocksGetBlocksPerDay
    blocksGetAverageBlockTime
    beetsGetBeetsPrice
}

query GetTokens {
    tokens: tokenGetTokens {
        address
        name
        symbol
        decimals
        chainId
        logoURI
        priority
        tradable
    }
}

query GetTokenPrices {
    tokenPrices: tokenGetCurrentPrices {
        price
        address
    }
}

query GetTokensDynamicData($addresses: [String!]!) {
    dynamicData: tokenGetTokensDynamicData(addresses: $addresses) {
        ath
        atl
        fdv
        high24h
        id
        low24h
        marketCap
        price
        priceChange24h
        priceChangePercent7d
        priceChangePercent14d
        priceChangePercent24h
        priceChangePercent30d
        tokenAddress
        updatedAt
    }
}

query GetFbeetsRatio {
    ratio: beetsGetFbeetsRatio
}

query GetProtocolData {
    protocolData: protocolMetrics {
        totalLiquidity
        totalSwapVolume
        totalSwapFee
        poolCount
        swapFee24h
        swapVolume24h
    }
    beetsPrice: beetsGetBeetsPrice
}

query GetBlocksPerDay {
    blocksPerDay: blocksGetBlocksPerDay
    avgBlockTime: blocksGetAverageBlockTime
}

query GetBeetsPrice {
    beetsPrice: beetsGetBeetsPrice
}
